### ISSUE TITLE
data-settings attribute value has to wrapped with single quote?

### ISSUE THREAD

**Issue by haojia321** [SAP/openui5-sample-app#45] opened 2019-03-19 17:58 UTC
data-settings attribute value has to wrapped with single quote. Rest of the attribute value can be wrapped with conventional double quote. For example below: sap.ui.demo.todo can be wrapped with double quote. But the value of data-settings cannot. I understand this might because of the json object is using double quote. But it is a convention we use double quote for attribute values in html markup.

<div data-sap-ui-component data-name="sap.ui.demo.todo" data-id="container" data-settings='{"id" : "todo"}'></div>

https://github.com/SAP/openui5-sample-app/blob/12b66d87b1d96929fb3cdf8252d083d64a9bbd1d/webapp/index.html#L23

**Comment by codeworrior** [comment] 2019-03-19 18:25
The use of single-quotes is just a proposal to simplify writing. If you prefer, you can use double quotes for the `data-settings` as well:
```html
 <div data-sap-ui-component 
      data-name="sap.ui.demo.todo" 
      data-id="container" 
      data-settings="{&quot;id&quot; : &quot;todo&quot;}"></div> 
```

**Comment by haojia321** [comment] 2019-03-19 18:43
@codeworrior 
I used ' instead of &quot; like below
 <div data-sap-ui-component 
      data-name="sap.ui.demo.todo" 
      data-id="container" 
      data-settings="{'id': 'todo'}"></div> 

It didnt work for me. Initially I didnt think it is the single/double quote issue. I spent like 15 mins trying to figure out the issue. Then I found it is single/double quote issue. I think other ppl might also run into this issue.

**Comment by codeworrior** [comment] 2019-03-19 18:49
I assume, you didn't get a helpful error message. That's a valid request, though.

Or we even re-think the "minimal code" idea again and use our JSTokenizer which accepts more dev-friendly syntax variants.

**Comment by bendkt** [comment] 2019-04-01 15:31
Hi haojia,

as this is not a bug of the sample application itself I am going to close this issue. Please file a bug report in openui5: https://github.com/SAP/openui5

Hereby please refer to: https://github.com/SAP/openui5/blob/master/CONTRIBUTING.md#report-an-issue

Best regards,
Benedikt

**Closed by bendkt** 2019-04-01 15:31 UTC
